# Generated by Django 3.1.3 on 2021-01-05 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, verbose_name='재고번호')),
                ('item_date', models.DateField(default=datetime.datetime.today, verbose_name='구매일자')),
                ('item_class', models.CharField(choices=[('사무', '사무'), ('전산', '전산'), ('장비', '장비')], max_length=100, verbose_name='품목')),
                ('item_name', models.CharField(max_length=100, verbose_name='품명')),
                ('item_price', models.IntegerField(verbose_name='가격')),
                ('item_condition', models.CharField(choices=[('A', '신품'), ('B', '중고품'), ('C', '대여'), ('D', '폐기')], max_length=100, verbose_name='제품상태')),
                ('manager_name', models.CharField(max_length=50, null=True, verbose_name='담당자')),
                ('manu_name', models.CharField(max_length=50, null=True, verbose_name='제조사')),
                ('model_number', models.CharField(max_length=50, null=True, verbose_name='모델넘버')),
                ('image', models.ImageField(default='item_image/no_image.png', null=True, upload_to='item_image/%Y/%m/', verbose_name='사진')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
