# Generated by Django 3.1.3 on 2021-01-22 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Class',
            fields=[
                ('item_class', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='품목')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Condition',
            fields=[
                ('item_condition', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='상태')),
            ],
        ),
        migrations.CreateModel(
            name='Item_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=11, verbose_name='재고번호')),
                ('item_date', models.DateField(default=datetime.datetime.today, verbose_name='구매일자')),
                ('item_name', models.CharField(max_length=100, verbose_name='품명')),
                ('item_price', models.PositiveIntegerField(verbose_name='가격')),
                ('item_count', models.PositiveSmallIntegerField(default=1, verbose_name='개수')),
                ('manager_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='담당자')),
                ('manu_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='제조사')),
                ('model_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='모델넘버')),
                ('image', models.ImageField(default='item_image/no_image.png', null=True, upload_to='item_image/%Y/%m/', verbose_name='사진')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_user', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_group', to='auth.group', verbose_name='부서명')),
                ('item_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_class', to='item_management.item_class', verbose_name='품목')),
                ('item_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_condition', to='item_management.item_condition', verbose_name='상태')),
            ],
        ),
    ]
