# Generated by Django 3.1.3 on 2021-01-22 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_code', models.CharField(max_length=100, verbose_name='사업번호')),
                ('entry_date', models.DateField(default=datetime.datetime.today, verbose_name='사업일자')),
                ('entry_name', models.CharField(max_length=100, verbose_name='사업명')),
                ('entry_condition', models.CharField(choices=[('A', '진행'), ('B', '종료'), ('C', '예정')], max_length=100, verbose_name='사업상태')),
                ('manager_name', models.CharField(max_length=50, verbose_name='담당자')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
