# Generated by Django 3.1.3 on 2021-01-05 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_code', models.CharField(max_length=100, verbose_name='재고번호')),
                ('entry_date', models.DateField(default=datetime.datetime.today, verbose_name='사업일자')),
                ('entry_name', models.CharField(max_length=100, verbose_name='품명')),
                ('entry_condition', models.CharField(choices=[('A', '진행'), ('B', '종료'), ('C', '예정')], max_length=100, verbose_name='사업상태')),
                ('manager_name', models.CharField(max_length=50, verbose_name='담당자')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author_entry', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_entry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
