# Generated by Django 3.1.3 on 2021-01-20 19:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_code', models.CharField(max_length=100, verbose_name='사업번호')),
                ('entry_date', models.DateField(default=datetime.datetime.today, verbose_name='사업일자')),
                ('entry_name', models.CharField(max_length=100, verbose_name='사업명')),
                ('entry_condition', models.CharField(choices=[('A', '진행'), ('B', '종료'), ('C', '예정')], max_length=100, verbose_name='사업상태')),
                ('manager_name', models.CharField(max_length=50, verbose_name='담당자')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry_Plus_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_id', to='entry_management.entry_info')),
            ],
        ),
    ]
