# Generated by Django 3.1.3 on 2021-01-20 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_plus_item',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='item_management.item_info', unique=True),
        ),
        migrations.AddField(
            model_name='entry_info',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entry', to=settings.AUTH_USER_MODEL),
        ),
    ]
