# Generated by Django 3.1.3 on 2021-01-05 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_management',
            name='author_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entry', to=settings.AUTH_USER_MODEL),
        ),
    ]
