# Generated by Django 3.1.3 on 2021-01-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry_management', '0002_auto_20210111_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Plus_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_id', to='entry_management.entry_info')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='item_management.item_info')),
            ],
        ),
    ]
