# Generated by Django 3.1.3 on 2021-01-05 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry_management', '0002_auto_20210105_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry_management',
            new_name='Entry_Info',
        ),
    ]
