# Generated by Django 3.1.3 on 2021-01-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_management', '0001_initial'),
        ('entry_management', '0003_entry_plus_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_plus_item',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='item_management.item_info', unique=True),
        ),
    ]
