# Generated by Django 3.1.4 on 2021-01-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_management', '0003_auto_20210105_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_info',
            name='entry_code',
            field=models.CharField(max_length=100, verbose_name='사업번호'),
        ),
        migrations.AlterField(
            model_name='entry_info',
            name='entry_name',
            field=models.CharField(max_length=100, verbose_name='사업명'),
        ),
    ]
